In [3]:
import pandas as pd
from sqlalchemy import create_engine, Integer

# Definir o caminho para o CSV
caminho_csv = '../final_data/cliente_final.csv'

# Ler o CSV com os dados
df_cliente = pd.read_csv(caminho_csv)

# Criar a conexão com o banco de dados (exemplo para PostgreSQL)
# Substitua 'username', 'password', 'localhost', 'mydatabase' com seus dados reais
engine = create_engine('postgresql://magazord_user:magazord@localhost:5432/magazord')

# Carregar os dados para a tabela 'clientes' no banco de dados
# A opção 'if_exists="replace"' vai substituir a tabela caso ela já exista, mas pode ser 'append' para adicionar aos dados existentes
df_cliente.to_sql('clientes', engine, index=False, if_exists='append', dtype={'id_cliente': Integer})

print("Dados carregados com sucesso!")

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "nome" of relation "clientes" does not exist
LINE 1: INSERT INTO clientes (nome, sobrenome, email, telefone, id) ...
                              ^

[SQL: INSERT INTO clientes (nome, sobrenome, email, telefone, id) VALUES (%(nome__0)s, %(sobrenome__0)s, %(email__0)s, %(telefone__0)s, %(id__0)s), (%(nome__1)s, %(sobrenome__1)s, %(email__1)s, %(telefone__1)s, %(id__1)s), (%(nome__2)s, %(sobrenome__2)s, % ... 84165 characters truncated ... s, %(id__998)s), (%(nome__999)s, %(sobrenome__999)s, %(email__999)s, %(telefone__999)s, %(id__999)s)]
[parameters: {'telefone__0': '(23) 8354-9059', 'sobrenome__0': 'Zyon', 'id__0': 1, 'email__0': 'AALINEZYON@gmail.com', 'nome__0': 'Aaline', 'telefone__1': '(18) 3183-4770', 'sobrenome__1': 'Zuziane', 'id__1': 2, 'email__1': 'AARAOZUZIANE@outlook.com', 'nome__1': 'Aarao', 'telefone__2': '(22) 6077-6114', 'sobrenome__2': 'Zuzi', 'id__2': 3, 'email__2': 'AARONZUZI@gmail.com', 'nome__2': 'Aaron', 'telefone__3': '(42) 2127-7981', 'sobrenome__3': 'Zuzete', 'id__3': 4, 'email__3': 'ABAZUZETE@yahoo.com', 'nome__3': 'Aba', 'telefone__4': '(47) 5908-0457', 'sobrenome__4': 'Zuzane', 'id__4': 5, 'email__4': 'ABADEZUZANE@terra.com', 'nome__4': 'Abade', 'telefone__5': '(15) 3598-8906', 'sobrenome__5': 'Zuzana', 'id__5': 6, 'email__5': 'ABADIZUZANA@terra.com', 'nome__5': 'Abadi', 'telefone__6': '(49) 7275-0590', 'sobrenome__6': 'Zuza', 'id__6': 7, 'email__6': 'ABADIAZUZA@hotmail.com', 'nome__6': 'Abadia', 'telefone__7': '(49) 4663-3099', 'sobrenome__7': 'Zusete', 'id__7': 8, 'email__7': 'ABADIASZUSETE@yahoo.com', 'nome__7': 'Abadias', 'telefone__8': '(49) 7609-9912', 'sobrenome__8': 'Zusane', 'id__8': 9, 'email__8': 'ABADIOZUSANE@gmail.com', 'nome__8': 'Abadio', 'telefone__9': '(40) 0357-6033', 'sobrenome__9': 'Zusana', 'id__9': 10, 'email__9': 'ABAETEZUSANA@yahoo.com', 'nome__9': 'Abaete' ... 4900 parameters truncated ... 'telefone__990': '(28) 2521-0421', 'sobrenome__990': 'Yvete', 'id__990': 991, 'email__990': 'ADEMIRESYVETE@terra.com', 'nome__990': 'Ademires', 'telefone__991': '(16) 5167-4501', 'sobrenome__991': 'Yves', 'id__991': 992, 'email__991': 'ADEMIRIOYVES@gmail.com', 'nome__991': 'Ademirio', 'telefone__992': '(42) 2531-6346', 'sobrenome__992': 'Yverson', 'id__992': 993, 'email__992': 'ADEMIROYVERSON@outlook.com', 'nome__992': 'Ademiro', 'telefone__993': '(38) 0111-2050', 'sobrenome__993': 'Yvens', 'id__993': 994, 'email__993': 'ADEMIRSOYVENS@hotmail.com', 'nome__993': 'Ademirso', 'telefone__994': '(12) 0121-1018', 'sobrenome__994': 'Yvelize', 'id__994': 995, 'email__994': 'ADEMIRSONYVELIZE@yahoo.com', 'nome__994': 'Ademirson', 'telefone__995': '(38) 3506-9954', 'sobrenome__995': 'Yvelise', 'id__995': 996, 'email__995': 'ADEMIRTONYVELISE@outlook.com', 'nome__995': 'Ademirton', 'telefone__996': '(49) 6589-8263', 'sobrenome__996': 'Yve', 'id__996': 997, 'email__996': 'ADEMISYVE@gmail.com', 'nome__996': 'Ademis', 'telefone__997': '(11) 0947-4045', 'sobrenome__997': 'Yvany', 'id__997': 998, 'email__997': 'ADEMISIAYVANY@yahoo.com', 'nome__997': 'Ademisia', 'telefone__998': '(30) 0909-9218', 'sobrenome__998': 'Yvanna', 'id__998': 999, 'email__998': 'ADEMISIOYVANNA@outlook.com', 'nome__998': 'Ademisio', 'telefone__999': '(22) 7932-8734', 'sobrenome__999': 'Yvanir', 'id__999': 1000, 'email__999': 'ADEMISONYVANIR@gmail.com', 'nome__999': 'Ademison'}]
(Background on this error at: https://sqlalche.me/e/20/f405)